# Generated by Django 2.2.4 on 2021-05-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_auto_20210525_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_show',
            old_name='desc',
            new_name='description',
        ),
    ]
