# Generated by Django 2.2.4 on 2021-05-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0003_auto_20210525_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_show',
            new_name='Shows',
        ),
    ]
