# Generated by Django 2.2.4 on 2021-05-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
        migrations.DeleteModel(
            name='Auther',
        ),
        migrations.AddField(
            model_name='authers',
            name='books',
            field=models.ManyToManyField(related_name='authers', to='books_authors_app.Books'),
        ),
    ]
